import { jsbasic } from "./scripts/JsBasics.js";
import { numbersMath } from "./scripts/NumbersAndMath.js";
import { string } from "./scripts/Strings.js";
import { htmlcssReview } from "./scripts/HTMLCSSReview.js";
import { variaBles } from "./scripts/Variables.js";
import { booleansAndIfStatements } from "./scripts/BooleansAndIfStatements.js";
import { func_Tion } from "./scripts/Functions.js";
import { obJects } from "./scripts/Objects.js";
import { dom } from "./scripts/DOM.js";
import { htmlCss } from "./scripts/htmlcss_js.js";

jsbasic();
numbersMath();
string();
htmlcssReview();
variaBles();
booleansAndIfStatements();
func_Tion();
obJects();
dom();
htmlCss();
