import { jsbasic } from "./scripts/JsBasics.js";
import { numbersMath } from "./scripts/NumbersAndMath.js";
import { string } from "./scripts/Strings.js";
import { htmlCssReview } from "./scripts/HtmlCssReview.js";
import { variaBles } from "./scripts/Variables.js";
import { booleansAndIfStatements } from "./scripts/BooleansAndIfStatements.js";
import { function_ } from "./scripts/Functions.js";
import { obJects } from "./scripts/Objects.js";
import { dom } from "./scripts/DOM.js";
import { htmlCssJs } from "./scripts/HtmlCssJs.js";

jsbasic();
numbersMath();
string();
htmlCssReview();
variaBles();
booleansAndIfStatements();
function_();
obJects();
dom();
htmlCssJs();
